### ISSUE TITLE
Suporte a plural ou texto condicional

### ISSUE THREAD

**Issue by pretodev** [davidsdearaujo/localization#11]
Estou trabalhando em um projeto que está em transição de arquitetura e estamos mudando a biblioteca de internalização para esta por conta da modularização. Porém a biblioteca antiga tem suporte a plurais.

Assim, queria contribuir com a adição deste suporte caso for do interesse do time.

Minha proposta seria adicionar algo da seguinte forma:

**No arquivo de tradução**
```json
"results": "%s %b{Resultados:Resultado} encontrados"
```

**No código**
```dart
"results".i18n(["3", true]);
```

**Comment by toshiossada** [comment]
opa @pretodev Abri um PR https://github.com/davidsdearaujo/localization/pull/12

**Comment by toshiossada** [comment]
irá ficar

### No arquivo de tradução:

```json
{
  "resultado_encontrado": "%s %b{Resultados:Resultado} %b{encontrados:encontrado}"
}
```

### No arquivo dart:

```dart
'resultado_encontrado'.i18n(args: [3], conditions: true, true])
```

o `conditions` tem que passar true/false se maneira posicional

**Comment by LucienCorreia** [comment]
Tenho uma situação interessante pra isso da pluralização

caso eu queira 4 contextos de texto:

- para quando é zero
- para quando é um
- para quando é de 2 até 99
- para quando é 100 ou mais

ex:

- Nenhuma notificação
- Uma notificação
- 10 notificações
- Muitas notificações

Assim teria no template algo como:

```json
{
"notification": "[0,0] Nenhuma notificação|[1,1] Uma notificação|[2,99] %s notificações|[100,*] Muitas notificações"
}
```

e na assinatura do método retiraria o `conditions` e passaria somente o valor que quer se utilizar:

```dart
'notification'.i18n(args: [3], 76) // 76 notificações
```

**Comment by toshiossada** [comment]
@LucienCorreia vamos analisar essa possibilidade de ter uma condição de multiplas escolhas baseada em um range de valores
