### ISSUE TITLE
vscode autocomplete does not work 

### ISSUE THREAD

**Issue by isorensen** [davidsdearaujo/localization#5]
# Summary

When calling "string".i18n(), VSCode does not show localization package in autocomplete import helper.

## Screenshots

![image](https://user-images.githubusercontent.com/3399976/91640223-4360db80-e9f2-11ea-9f04-617ed5bcbc10.png)

## Expected

Auto import for package shows in helper, like example below:  
![image](https://user-images.githubusercontent.com/3399976/91640245-7a36f180-e9f2-11ea-8cd9-fa9919007b42.png)

**Comment by davidsdearaujo** [comment]
This is a problem with Dart's intelisense for VSCode that occurs for all extensions.
Track changes in this issue: https://github.com/dart-lang/sdk/issues/38894
